server:
  port: 8081
  servlet:
    context-path: /flygon

spring:
  profiles:
    active: dev
  application:
    name: '@project.artifactId@'
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"

springdoc:
  version: '@project.version@'
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    #oauth:
    #  clientId: newClient
    #  clientSecret: newClientSecret
  #oAuthFlow:
  #  authorizationUrl: http://localhost:8083/auth/realms/springdoc/protocol/openid-connect/auth
  #  tokenUrl: http://localhost:8083/auth/realms/springdoc/protocol/openid-connect/token
  show-actuator: true
  group-configs:
    - group: sys 系统管理
      paths-to-match: /sys/**

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-handlers-package:  com.power4j.flygon.common.data.mybatis.handler
