management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

ji-boot:
  security:
    api:
      permit-all: false

spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:10.11.12.8}:${MYSQL_PORT:5306}/${MYSQL_DB:ji_boot}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: ${MYSQL_USER:root}
      password: ${MYSQL_USER:root}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          enabled: true
          config:
            multi-statement-allow: true
        config:
          enabled: true
        slf4j:
          enabled: true
        encoding:
          enabled: true

logging:
  level:
    org:
      springframework:
        security: info
    com:
      power4j:
        ji:
          admin:
            modules: debug
          common:
            security: info
            schedule:
              quartz:
                listener: debug
